import { Grant, User, Application } from '../types';

export const DEMO_USER: User = {
  id: 1, email: 'demo@grants.local', full_name: 'Демо Пользователь',
  is_admin: true, notify_email: true, notify_telegram: false, notify_push: false,
  telegram_chat_id: null, created_at: new Date().toISOString(),
};

export const MOCK_GRANTS: Grant[] = [
  {
    id: 1, source_name: 'Президентский фонд культурных инициатив',
    source_url: 'https://фондкультурныхинициатив.рф',
    who_can_apply: 'НКО, юридические лица, ИП в сфере культуры и искусства',
    age_restrictions: null,
    max_amount: 10000000, max_amount_text: 'до 10 000 000 ₽',
    window_schedule: 'Два конкурса в год: весенний (март–апрель) и осенний (сентябрь–октябрь)',
    typical_docs: 'Заявка, смета, устав организации, справка об отсутствии задолженностей',
    reporting: 'Промежуточный и итоговый отчёт с подтверждающими документами',
    critical_notes: 'Обязательно наличие собственного вклада не менее 5% от суммы гранта',
    submission_target: 'Онлайн через платформу фонда',
    category: 'nko', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 1, deadline_date: '2026-04-15', window_label: 'Весенний конкурс 2026', is_confirmed: true, source: 'official' }],
    nearest_deadline: '2026-04-15', deadline_label: 'Весенний конкурс 2026',
  },
  {
    id: 2, source_name: 'Грант Росмолодёжи',
    source_url: 'https://росмолодёжь.рф',
    who_can_apply: 'Молодёжь от 14 до 35 лет, молодёжные НКО',
    age_restrictions: '14–35 лет',
    max_amount: 1500000, max_amount_text: 'до 1 500 000 ₽',
    window_schedule: 'Форум Росмолодёжи — ежегодно летом',
    typical_docs: 'Паспорт, заявка с описанием проекта, смета, письмо поддержки',
    reporting: 'Отчёт по факту реализации проекта в течение 30 дней',
    critical_notes: 'Проект должен быть ориентирован на молодёжную аудиторию',
    submission_target: 'АИС «Молодёжь России»',
    category: 'individual', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 2, deadline_date: '2026-06-01', window_label: 'Форум 2026', is_confirmed: false, source: 'estimated' }],
    nearest_deadline: '2026-06-01', deadline_label: 'Форум 2026',
  },
  {
    id: 3, source_name: 'Фонд «Сенатор»',
    source_url: null,
    who_can_apply: 'НКО, осуществляющие деятельность в социальной сфере',
    age_restrictions: null,
    max_amount: 3000000, max_amount_text: 'до 3 000 000 ₽',
    window_schedule: 'Ежеквартально',
    typical_docs: 'Заявка, устав, отчётность за прошлый год, описание проекта',
    reporting: 'Ежеквартальные отчёты о расходовании средств',
    critical_notes: 'Приоритет — проекты в регионах с низким социально-экономическим уровнем',
    submission_target: 'Email + почта',
    category: 'nko', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 3, deadline_date: '2026-03-31', window_label: 'I квартал 2026', is_confirmed: true, source: 'official' }],
    nearest_deadline: '2026-03-31', deadline_label: 'I квартал 2026',
  },
  {
    id: 4, source_name: 'Грант Мэра Москвы для НКО',
    source_url: 'https://www.mos.ru/donm/grants/',
    who_can_apply: 'НКО, зарегистрированные в г. Москве',
    age_restrictions: null,
    max_amount: 5000000, max_amount_text: 'до 5 000 000 ₽',
    window_schedule: 'Ежегодно, конкурс объявляется в феврале',
    typical_docs: 'Устав, выписка из ЕГРЮЛ, отчёт об исполнении предыдущих грантов',
    reporting: 'Ежеквартальные и итоговый финансовые отчёты',
    critical_notes: 'Организация должна работать в Москве не менее 2 лет',
    submission_target: 'Портал mos.ru',
    category: 'nko', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 4, deadline_date: '2026-03-20', window_label: 'Конкурс 2026', is_confirmed: true, source: 'official' }],
    nearest_deadline: '2026-03-20', deadline_label: 'Конкурс 2026',
  },
  {
    id: 5, source_name: 'Фонд президентских грантов',
    source_url: 'https://президентскиегранты.рф',
    who_can_apply: 'Некоммерческие организации любых форм',
    age_restrictions: null,
    max_amount: 20000000, max_amount_text: 'до 20 000 000 ₽',
    window_schedule: 'Два конкурса: первый — до марта, второй — до сентября',
    typical_docs: 'Заявка в системе, устав, финансовая отчётность за 2 года, ИНН',
    reporting: 'Содержательный и финансовый отчёт каждые 6 месяцев',
    critical_notes: 'Одна организация может получить не более двух грантов подряд',
    submission_target: 'Грантовая система presidents-grants.ru',
    category: 'nko', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [
      { id: 5, deadline_date: '2026-03-05', window_label: 'Первый конкурс 2026', is_confirmed: true, source: 'official' },
      { id: 6, deadline_date: '2026-09-10', window_label: 'Второй конкурс 2026', is_confirmed: true, source: 'official' },
    ],
    nearest_deadline: '2026-03-05', deadline_label: 'Первый конкурс 2026',
  },
  {
    id: 6, source_name: 'Грант Фонда Тимченко',
    source_url: 'https://timchenkofoundation.org',
    who_can_apply: 'НКО, работающие с пожилыми людьми или в сельской местности',
    age_restrictions: null,
    max_amount: 2000000, max_amount_text: 'до 2 000 000 ₽',
    window_schedule: 'Открытый конкурс раз в год (обычно осенью)',
    typical_docs: 'Заявка, описание проекта, опыт работы организации',
    reporting: 'Содержательный отчёт + медиаматериалы',
    critical_notes: 'Фонд поддерживает проекты в малых городах и сёлах',
    submission_target: 'Онлайн-форма на сайте фонда',
    category: 'nko', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 7, deadline_date: '2026-10-01', window_label: 'Конкурс 2026', is_confirmed: false, source: 'estimated' }],
    nearest_deadline: '2026-10-01', deadline_label: 'Конкурс 2026',
  },
  {
    id: 7, source_name: 'Субсидии Минэкономразвития для МСП',
    source_url: 'https://мойбизнес.рф',
    who_can_apply: 'Малый и средний бизнес, ИП',
    age_restrictions: null,
    max_amount: 500000, max_amount_text: 'до 500 000 ₽',
    window_schedule: 'Ежегодно, приём заявок в I–II кварталах',
    typical_docs: 'Бизнес-план, выписка ЕГРИП/ЕГРЮЛ, финансовая отчётность',
    reporting: 'Отчёт о целевом использовании средств через 12 месяцев',
    critical_notes: 'Обязательно наличие расчётного счёта и отсутствие долгов перед бюджетом',
    submission_target: 'МФЦ или портал «Мой бизнес»',
    category: 'business', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 8, deadline_date: '2026-05-01', window_label: 'Приём 2026', is_confirmed: false, source: 'estimated' }],
    nearest_deadline: '2026-05-01', deadline_label: 'Приём 2026',
  },
  {
    id: 8, source_name: 'Грант «Агросила»',
    source_url: null,
    who_can_apply: 'Фермеры, сельхозкооперативы, жители сельской местности',
    age_restrictions: null,
    max_amount: 6000000, max_amount_text: 'до 6 000 000 ₽',
    window_schedule: 'Конкурс ежегодно весной',
    typical_docs: 'Бизнес-план, документы на землю, справка о доходах',
    reporting: 'Годовой отчёт с фотоматериалами реализованного проекта',
    critical_notes: 'Проект должен создавать не менее 3 новых рабочих мест',
    submission_target: 'Районный отдел Минсельхоза',
    category: 'business', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 9, deadline_date: '2026-04-30', window_label: 'Конкурс 2026', is_confirmed: false, source: 'estimated' }],
    nearest_deadline: '2026-04-30', deadline_label: 'Конкурс 2026',
  },
  {
    id: 9, source_name: 'Грант «Моя Россия» для физических лиц',
    source_url: 'https://moyarossiya.ru',
    who_can_apply: 'Физические лица, авторы творческих и социальных проектов',
    age_restrictions: '18–45 лет',
    max_amount: 300000, max_amount_text: 'до 300 000 ₽',
    window_schedule: 'Приём заявок круглогодично, отбор — ежеквартально',
    typical_docs: 'Заявка, паспорт, описание проекта, портфолио',
    reporting: 'Финансовый отчёт + публичная презентация результатов',
    critical_notes: 'Приоритет — проекты с социальным эффектом и тиражируемостью',
    submission_target: 'Онлайн-форма на сайте',
    category: 'individual', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 10, deadline_date: '2026-03-31', window_label: 'I квартал 2026', is_confirmed: true, source: 'official' }],
    nearest_deadline: '2026-03-31', deadline_label: 'I квартал 2026',
  },
  {
    id: 10, source_name: 'Социальный грант Сбера',
    source_url: 'https://sber.ru/grants',
    who_can_apply: 'НКО, физлица с социальными проектами',
    age_restrictions: null,
    max_amount: 1000000, max_amount_text: 'до 1 000 000 ₽',
    window_schedule: 'Два раза в год: весна и осень',
    typical_docs: 'Заявка, описание проекта, смета, данные об авторе / организации',
    reporting: 'Отчёт о реализации с медиаматериалами в течение 60 дней после завершения',
    critical_notes: 'Приоритет — экологические и образовательные проекты',
    submission_target: 'Онлайн через сайт Сбера',
    category: 'nko', is_active: true, last_scraped_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    deadlines: [{ id: 11, deadline_date: '2026-05-15', window_label: 'Весенний конкурс 2026', is_confirmed: false, source: 'estimated' }],
    nearest_deadline: '2026-05-15', deadline_label: 'Весенний конкурс 2026',
  },
];

export const MOCK_APPLICATION: Application = {
  id: 1, grant_id: 1, user_id: 1, status: 'draft', current_step: 1,
  wizard_data: {}, ai_hints: {}, created_at: new Date().toISOString(), updated_at: null,
};
